CREATE TABLE IF NOT EXISTS USER_GROUP (
							GROUP_NAME TEXT,
							GID INT,
							GROUP_LIST TEXT
							);
CREATE TABLE IF NOT EXISTS USER_PASSWD (
							USERNAME TEXT,
							UID INT PRIMARY_KEY,
							GID INT,
							INFO TEXT,
							HOME_DIR TEXT,
							SHELL TEXT
							);